'use client';

import { useState } from 'react';
import { usePathname, useSearchParams } from 'next/navigation';
import { useForm, useWatch } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Plus, RotateCcw } from 'lucide-react';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Dialog, DialogContent, DialogDescription, DialogTitle } from '@/components/ui/dialog';
import { EmptyState, Pagination } from '@/components/business/customer-ui';
import { ErrorState, LoadingState } from '@/components/common/error-state';
import { PermissionGate } from '@/components/common/permission-gate';
import { workersApi } from '@/lib/api/customers';
import { paymentsApi, prepaidApi, returnsApi } from '@/lib/api/finance';
import { ordersApi } from '@/lib/api/orders';
import { errorMessage } from '@/lib/api/errors';
import { formatMoney } from '@/lib/utils/money';
import { paymentInputSchema, type PaymentInput, type ReturnInput } from './schema';

const methodLabels={WECHAT:'微信',ALIPAY:'支付宝',CASH:'现金',BANK_CARD:'银行卡',OTHER:'其他'} as const;
const fieldClass='grid gap-4 [&_label>span]:mb-2 [&_label>span]:block [&_label>span]:text-xs [&_label>span]:text-[#66645f]';
const tableClass='w-full min-w-[880px] border-collapse text-xs [&_th]:border-b [&_th]:border-black/10 [&_th]:bg-[#fafaf8] [&_th]:px-4 [&_th]:py-3 [&_th]:text-left [&_th]:font-medium [&_th]:text-[#77756e] [&_td]:border-b [&_td]:border-black/5 [&_td]:px-4 [&_td]:py-3.5';
const localNow=()=>{const date=new Date();date.setMinutes(date.getMinutes()-date.getTimezoneOffset());return date.toISOString().slice(0,16);};

export function CashRecordsPage({kind}:{kind:'payment'|'prepaid'}){
  const payment=kind==='payment';const title=payment?'收款':'预存款';const permission=payment?'payments:create':'prepaid:deposit';
  const pathname=usePathname(),params=useSearchParams(),page=Number(params.get('page'))||1;
  const [open,setOpen]=useState(false),[draft,setDraft]=useState<PaymentInput>();const client=useQueryClient();
  const query=useQuery({queryKey:[kind,page],queryFn:async({signal})=>{const data=payment?await paymentsApi.list({page,pageSize:20},signal):await prepaidApi.list({page,pageSize:20},signal);return {...data,items:data.items.map((item)=>({...item,before:'receivableBefore' in item?item.receivableBefore:item.balanceBefore,after:'receivableAfter' in item?item.receivableAfter:item.balanceAfter}))};}});
  const workers=useQuery({queryKey:['workers',kind],queryFn:({signal})=>workersApi.list({pageSize:50,status:'ACTIVE'},signal)});
  const form=useForm<PaymentInput>({resolver:zodResolver(paymentInputSchema),defaultValues:{workerId:'',amount:'',paymentMethod:'WECHAT',occurredAt:localNow(),note:''}});
  const workerId=useWatch({control:form.control,name:'workerId'});const selected=workers.data?.items.find((item)=>item.id===workerId);
  const mutation=useMutation({mutationFn:async(input:PaymentInput)=>{if(payment)await paymentsApi.create(input,crypto.randomUUID());else await prepaidApi.create(input,crypto.randomUUID());},onSuccess:async()=>{toast.success(`${title}已登记`);setDraft(undefined);setOpen(false);form.reset({workerId:'',amount:'',paymentMethod:'WECHAT',occurredAt:localNow(),note:''});await Promise.all([client.invalidateQueries({queryKey:[kind]}),client.invalidateQueries({queryKey:['workers']})]);},onError:(error)=>toast.error(errorMessage(error))});
  const items=query.data?.items||[];
  return <><header className="flex items-start justify-between gap-5"><div><h1>{title}</h1><p>{payment?'登记客户实际付款并实时冲减应收。':'登记客户预存资金，余额与欠款分别核算。'}</p></div><PermissionGate permission={permission}><Button onClick={()=>setOpen(true)}><Plus size={15}/>登记{title}</Button></PermissionGate></header>
    {query.isPending?<LoadingState label={`正在加载${title}记录…`}/>:query.isError?<ErrorState error={query.error} retry={()=>void query.refetch()}/>:<section className="overflow-hidden border-y border-black/10"><div className="overflow-auto">{items.length?<table className={tableClass}><thead><tr><th>流水号 / 时间</th><th>油漆工</th><th>金额</th><th>付款方式</th><th>{payment?'收款前应收':'预存前余额'}</th><th>{payment?'剩余应收':'预存后余额'}</th><th>操作人</th><th>备注</th></tr></thead><tbody>{items.map((item)=><tr className="hover:bg-[#f7f7f5]" key={item.id}><td><strong className="block font-medium text-[#22211f]">{item.transactionNo}</strong><small className="mt-1 block text-[10px] text-[#8a8985]">{new Date(item.occurredAt).toLocaleString('zh-CN')}</small></td><td>{item.workerName}</td><td className="font-medium tabular-nums">{formatMoney(item.amount)}</td><td>{methodLabels[item.paymentMethod]}</td><td className="tabular-nums">{formatMoney(item.before)}</td><td className="font-medium tabular-nums">{formatMoney(item.after)}</td><td>{item.operatorName}</td><td className="max-w-48 truncate text-[#77756e]">{item.note||'—'}</td></tr>)}</tbody></table>:<EmptyState title={`暂无${title}记录`} description={`登记第一笔${title}后会显示在这里。`}/>}</div><Pagination page={query.data.page} pageSize={query.data.pageSize} total={query.data.total} href={next=>{const value=new URLSearchParams(params);value.set('page',String(next));return `${pathname}?${value}`;}}/></section>}
    <Dialog open={open} onOpenChange={(value)=>{setOpen(value);if(!value)setDraft(undefined);}}><DialogContent><DialogTitle>{draft?`确认${title}`:`登记${title}`}</DialogTitle><DialogDescription>{draft?'核对客户、金额和付款方式，确认后正式入账。':payment?'收款金额不能超过客户当前应收。':'预存款不会直接冲减客户欠款。'}</DialogDescription>{draft?<div><dl className="grid gap-3 rounded-xl bg-[#f2f2ef] p-4 text-sm [&>div]:flex [&>div]:justify-between"><div><dt>油漆工</dt><dd>{selected?.name}</dd></div><div><dt>{payment?'当前应收':'当前预存'}</dt><dd>{formatMoney(payment?selected?.receivable||'0':selected?.prepaidBalance||'0')}</dd></div><div><dt>本次金额</dt><dd className="font-medium">{formatMoney(draft.amount)}</dd></div><div><dt>付款方式</dt><dd>{methodLabels[draft.paymentMethod]}</dd></div></dl><div className="mt-5 flex justify-end gap-2"><Button variant="outline" onClick={()=>setDraft(undefined)}>返回修改</Button><Button disabled={mutation.isPending} onClick={()=>mutation.mutate(draft)}>{mutation.isPending?'正在提交…':'确认入账'}</Button></div></div>:<form className={fieldClass} onSubmit={form.handleSubmit(setDraft)}><label><span>油漆工 *</span><select className="h-10 w-full rounded-lg border border-black/15 bg-white px-3 text-sm" {...form.register('workerId')}><option value="">请选择油漆工</option>{workers.data?.items.map((item)=><option value={item.id} key={item.id}>{item.name} · 应收 {formatMoney(item.receivable)} · 预存 {formatMoney(item.prepaidBalance)}</option>)}</select>{form.formState.errors.workerId&&<small className="text-[#a34e40]">{form.formState.errors.workerId.message}</small>}</label>{selected&&<div className="grid grid-cols-2 gap-3 rounded-xl bg-[#f2f2ef] p-4 text-xs"><span>当前应收<strong className="mt-1 block text-sm">{formatMoney(selected.receivable)}</strong></span><span>预存余额<strong className="mt-1 block text-sm">{formatMoney(selected.prepaidBalance)}</strong></span></div>}<label><span>{title}金额 *</span><Input inputMode="decimal" placeholder="0.00" {...form.register('amount')}/>{form.formState.errors.amount&&<small className="text-[#a34e40]">{form.formState.errors.amount.message}</small>}</label><label><span>付款方式 *</span><select className="h-10 w-full rounded-lg border border-black/15 bg-white px-3 text-sm" {...form.register('paymentMethod')}>{Object.entries(methodLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label><span>时间 *</span><Input type="datetime-local" {...form.register('occurredAt')}/></label><label><span>备注</span><Input placeholder="选填" {...form.register('note')}/></label><div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={()=>setOpen(false)}>取消</Button><Button>下一步确认</Button></div></form>}</DialogContent></Dialog>
  </>;
}

export function ReturnsPage(){
  const pathname=usePathname(),params=useSearchParams(),page=Number(params.get('page'))||1;
  const [open,setOpen]=useState(false),[orderId,setOrderId]=useState(''),[quantities,setQuantities]=useState<Record<string,string>>({}),[note,setNote]=useState('');const client=useQueryClient();
  const query=useQuery({queryKey:['returns',page],queryFn:({signal})=>returnsApi.list({page,pageSize:20},signal)});
  const orders=useQuery({queryKey:['orders','return-options'],queryFn:({signal})=>ordersApi.list({pageSize:50},signal)});const order=orders.data?.items.find((item)=>item.id===orderId);
  const mutation=useMutation({mutationFn:(input:ReturnInput)=>returnsApi.create(input,crypto.randomUUID()),onSuccess:async(item)=>{toast.success(item.status==='PENDING'?'退料申请已提交':'退料已确认');setOpen(false);setOrderId('');setQuantities({});setNote('');await Promise.all([client.invalidateQueries({queryKey:['returns']}),client.invalidateQueries({queryKey:['workers']})]);},onError:(error)=>toast.error(errorMessage(error))});
  const submit=()=>{if(!order)return;const items=Object.entries(quantities).filter(([,quantity])=>Number(quantity)>0).map(([materialId,quantity])=>({materialId,quantity}));mutation.mutate({orderId:order.id,items,note});};
  return <><header className="flex items-start justify-between gap-5"><div><h1>退料记录</h1><p>从原用料单选择材料退回，系统自动校验可退数量。</p></div><PermissionGate permission="returns:request"><Button onClick={()=>setOpen(true)}><RotateCcw size={15}/>发起退料</Button></PermissionGate></header>
  {query.isPending?<LoadingState label="正在加载退料记录…"/>:query.isError?<ErrorState error={query.error} retry={()=>void query.refetch()}/>:<section className="overflow-hidden border-y border-black/10"><div className="overflow-auto">{query.data.items.length?<table className={tableClass}><thead><tr><th>退料单 / 时间</th><th>原用料单</th><th>油漆工</th><th>退料内容</th><th>退料金额</th><th>冲减应收</th><th>状态</th><th>操作人</th></tr></thead><tbody>{query.data.items.map((item)=><tr className="hover:bg-[#f7f7f5]" key={item.id}><td><strong className="block font-medium">{item.returnNo}</strong><small className="mt-1 block text-[10px] text-[#8a8985]">{new Date(item.createdAt).toLocaleString('zh-CN')}</small></td><td>{item.orderNo}</td><td>{item.workerName}</td><td>{item.items.map((line)=>`${line.materialName} × ${line.quantity}`).join('、')}</td><td className="tabular-nums">{formatMoney(item.amount)}</td><td className="tabular-nums text-[#558063]">{formatMoney(item.receivableReduction)}</td><td><span className="rounded-md bg-[#efeeeb] px-2 py-1 text-[10px]">{item.status==='PENDING'?'待确认':item.status==='CONFIRMED'?'已确认':'已冲销'}</span></td><td>{item.operatorName}</td></tr>)}</tbody></table>:<EmptyState title="暂无退料记录" description="从原用料单发起退料后会显示在这里。"/>}</div><Pagination page={query.data.page} pageSize={query.data.pageSize} total={query.data.total} href={next=>{const value=new URLSearchParams(params);value.set('page',String(next));return `${pathname}?${value}`;}}/></section>}
  <Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-w-[680px]"><DialogTitle>从原用料单发起退料</DialogTitle><DialogDescription>退料数量不能超过原购买数量减去历史已退数量。</DialogDescription><div className={fieldClass}><label><span>原用料单 *</span><select className="h-10 w-full rounded-lg border border-black/15 bg-white px-3 text-sm" value={orderId} onChange={(event)=>{setOrderId(event.target.value);setQuantities({});}}><option value="">请选择原用料单</option>{orders.data?.items.map((item)=><option value={item.id} key={item.id}>{item.orderNo} · {item.workerName} · {formatMoney(item.finalAmount)}</option>)}</select></label>{order&&<div className="overflow-hidden rounded-xl border border-black/10"><div className="grid grid-cols-[1fr_90px_120px] bg-[#fafaf8] px-4 py-2.5 text-xs text-[#77756e]"><span>材料</span><span>原数量</span><span>本次退料</span></div>{order.items.map((item)=><div className="grid grid-cols-[1fr_90px_120px] items-center border-t border-black/5 px-4 py-3 text-xs" key={item.materialId}><span><strong className="block font-medium">{item.materialName}</strong><small className="mt-1 block text-[#8a8985]">{item.specification} · {formatMoney(item.unitPrice)}/{item.unit}</small></span><span>{item.quantity} {item.unit}</span><Input className="h-8" inputMode="decimal" placeholder="0" value={quantities[item.materialId]||''} onChange={(event)=>setQuantities((value)=>({...value,[item.materialId]:event.target.value}))}/></div>)}</div>}<label><span>备注</span><Input value={note} onChange={(event)=>setNote(event.target.value)} placeholder="退料原因，选填"/></label><div className="flex justify-end gap-2"><Button variant="outline" onClick={()=>setOpen(false)}>取消</Button><Button disabled={!order||mutation.isPending||!Object.values(quantities).some((value)=>Number(value)>0)} onClick={submit}>{mutation.isPending?'正在提交…':'确认退料'}</Button></div></div></DialogContent></Dialog></>;
}
