'use client';
import { useState } from 'react';
import Link from 'next/link';
import { useQuery } from '@tanstack/react-query';
import { ArrowLeft, Edit3, MapPin, Phone, UsersRound } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { StatusBadge } from '@/components/business/customer-ui';
import { ErrorState, LoadingState } from '@/components/common/error-state';
import { PermissionGate } from '@/components/common/permission-gate';
import { formatMoney } from '@/lib/utils/money';
import { projectsApi, teamsApi, workersApi } from '@/lib/api/customers';
import { ProjectForm, TeamForm, WorkerForm } from './forms';
import { DisabledBusinessAction } from './list-pages';

const panelClass = 'rounded-[14px] border border-[#e7e7e3] bg-white p-[22px]';
const linkedListClass = 'mt-4 [&>a]:flex [&>a]:items-center [&>a]:gap-3 [&>a]:border-b [&>a]:border-[#eef0ea] [&>a]:px-1 [&>a]:py-3.5 [&>a]:text-[#687861] [&>a:last-child]:border-0 [&_strong]:text-xs [&_strong]:text-[#46523f] [&_small]:mt-1 [&_small]:flex [&_small]:items-center [&_small]:gap-1 [&_small]:text-[10px] [&_small]:text-[#959c90] [&_em]:ml-auto [&_em]:text-[10px] [&_em]:not-italic';

function DetailHeader({ back,eyebrow,title,subtitle,status,children }:{back:string;eyebrow:string;title:string;subtitle:string;status:React.ReactNode;children:React.ReactNode}) { return <><Link className="mb-5 inline-flex items-center gap-1.5 text-xs text-[#7d8578]" href={back}><ArrowLeft size={15}/>返回列表</Link><header className="mb-6 flex items-end justify-between gap-5 max-[600px]:flex-col max-[600px]:items-start"><div><p className="mb-2 text-xs text-[#92928d]">{eyebrow}</p><div className="flex items-center gap-3"><h1 className="font-serif text-[30px] font-medium">{title}</h1>{status}</div><p className="mt-2 text-xs text-[#858d80]">{subtitle}</p></div><div className="flex items-center gap-2">{children}</div></header></>; }
function Summary({ items }:{items:{label:string;value:string;tone?:string}[]}) { return <section className="mb-4 grid grid-cols-5 gap-2.5 max-[1200px]:grid-cols-3 max-[600px]:grid-cols-2">{items.map(x=><article className="min-h-[105px] rounded-xl border border-[#e7e7e3] bg-white p-[18px] max-[600px]:min-h-[90px]" key={x.label}><span className="block text-[11px] text-[#888f83]">{x.label}</span><strong className={`mt-5 block text-[19px] font-medium ${x.tone === 'positive' ? 'text-[#558063]' : x.tone === 'danger' ? 'text-[#bc7467]' : ''}`}>{x.value}</strong></article>)}</section>; }
function Placeholder({ title }:{title:string}) { return <div className="flex min-h-[200px] flex-col items-center justify-center gap-3 text-center text-[#92998c]"><strong className="text-[#58644f]">{title}</strong><p className="text-xs">该业务数据将在对应阶段接入，不会用演示数据冒充正式账务。</p></div>; }

export function WorkerDetail({ id }:{id:string}) {
  const [tab,setTab]=useState('ledger'),[edit,setEdit]=useState(false);const worker=useQuery({queryKey:['workers',id],queryFn:({signal})=>workersApi.get(id,signal)});const teams=useQuery({queryKey:['teams','options'],queryFn:({signal})=>teamsApi.list({pageSize:50},signal)});const projects=useQuery({queryKey:['projects','worker',id],queryFn:({signal})=>projectsApi.list({pageSize:50},signal)});
  if(worker.isPending)return <LoadingState/>;if(worker.isError)return <ErrorState error={worker.error} retry={()=>void worker.refetch()}/>;const item=worker.data;const linked=projects.data?.items.filter(x=>x.workerIds.includes(id))||[];
  const tabs=[['ledger','往来账'],['orders','用料记录'],['payments','收款记录'],['returns','退料记录'],['projects','工地项目'],['pricing','客户价格'],['info','基本信息']];
  return <><DetailHeader back="/workers" eyebrow="油漆工详情" title={item.name} subtitle={`${item.phone} · ${item.teamName||'独立油漆工'}`} status={<StatusBadge status={item.status}/>}><DisabledBusinessAction type="order"/><DisabledBusinessAction type="payment"/><PermissionGate permission="workers:write"><Button onClick={()=>setEdit(true)}><Edit3 size={15}/>编辑资料</Button></PermissionGate></DetailHeader><Summary items={[{label:'累计用料',value:formatMoney(item.materialTotal)},{label:'累计付款',value:formatMoney(item.paymentTotal)},{label:'累计退料',value:formatMoney(item.returnTotal)},{label:'预存余额',value:formatMoney(item.prepaidBalance),tone:'positive'},{label:'当前应收',value:formatMoney(item.receivable),tone:Number(item.receivable)>0?'danger':''}]}/><section className={panelClass}><div className="flex gap-1 overflow-auto border-b border-[#e7e7e3] [&>button]:whitespace-nowrap [&>button]:border-0 [&>button]:bg-transparent [&>button]:px-3.5 [&>button]:pb-3 [&>button]:text-[#858c80] [&>button[aria-selected=true]]:border-b-2 [&>button[aria-selected=true]]:border-[#57764c] [&>button[aria-selected=true]]:font-semibold [&>button[aria-selected=true]]:text-[#3f5b35]" role="tablist">{tabs.map(([key,label])=><button role="tab" aria-selected={tab===key} key={key} onClick={()=>setTab(key)}>{label}</button>)}</div><div className="min-h-[230px] pt-5">{tab==='info'?<dl className="m-0 grid grid-cols-2 gap-[22px] max-[600px]:grid-cols-1 [&_dt]:text-[11px] [&_dt]:text-[#8e9589] [&_dd]:mt-2 [&_dd]:flex [&_dd]:items-center [&_dd]:gap-1 [&_dd]:text-[13px] [&_dd]:text-[#485043]"><div><dt>姓名</dt><dd>{item.name}</dd></div><div><dt>手机号</dt><dd>{item.phone}</dd></div><div><dt>微信号</dt><dd>{item.wechat||'未填写'}</dd></div><div><dt>所属施工队</dt><dd>{item.teamName||'无'}</dd></div><div className="col-span-full max-[600px]:col-span-1"><dt>备注</dt><dd>{item.note||'暂无备注'}</dd></div></dl>:tab==='projects'?linked.length?<div className={linkedListClass}>{linked.map(x=><Link key={x.id} href={`/projects/${x.id}`}><MapPin size={17}/><span><strong>{x.name}</strong><small>{x.address}</small></span><StatusBadge status={x.status}/></Link>)}</div>:<Placeholder title="暂无关联项目"/>:<Placeholder title={tabs.find(x=>x[0]===tab)?.[1]||''}/>}</div></section><WorkerForm open={edit} onOpenChange={setEdit} value={item} teams={teams.data?.items||[]}/></>;
}

export function TeamDetail({ id }:{id:string}) {
  const [edit,setEdit]=useState(false);const team=useQuery({queryKey:['teams',id],queryFn:({signal})=>teamsApi.get(id,signal)});const workers=useQuery({queryKey:['workers','team',id],queryFn:({signal})=>workersApi.list({teamId:id,pageSize:50},signal)});const projects=useQuery({queryKey:['projects','team',id],queryFn:({signal})=>projectsApi.list({pageSize:50},signal)});if(team.isPending)return <LoadingState/>;if(team.isError)return <ErrorState error={team.error} retry={()=>void team.refetch()}/>;const item=team.data;const linked=projects.data?.items.filter(x=>x.teamId===id)||[];
  return <><DetailHeader back="/teams" eyebrow="施工队详情" title={item.name} subtitle={`${item.leader} · ${item.phone}`} status={<StatusBadge status={item.status}/>}><PermissionGate permission="workers:write"><Button onClick={()=>setEdit(true)}><Edit3 size={15}/>编辑资料</Button></PermissionGate></DetailHeader><Summary items={[{label:'成员数量',value:`${workers.data?.total??item.memberCount} 人`},{label:'累计用料',value:formatMoney(item.materialTotal)},{label:'累计付款',value:formatMoney(item.paymentTotal)},{label:'当前欠款',value:formatMoney(item.receivable),tone:Number(item.receivable)>0?'danger':''}]}/><div className="grid grid-cols-2 gap-3.5 max-[600px]:grid-cols-1"><section className={panelClass}><div className="flex items-start justify-between gap-4 [&_h2]:mb-1 [&_h2]:text-base [&_h2]:font-semibold [&_p]:text-xs [&_p]:text-[#a1a19b]"><div><h2>施工队成员</h2><p>账务仍归属每位油漆工</p></div></div><div className={linkedListClass}>{workers.data?.items.map(x=><Link href={`/workers/${x.id}`} key={x.id}><UsersRound size={17}/><span><strong>{x.name}</strong><small>{x.phone}</small></span><em>{formatMoney(x.receivable)}</em></Link>)}</div></section><section className={panelClass}><div className="flex items-start justify-between gap-4 [&_h2]:mb-1 [&_h2]:text-base [&_h2]:font-semibold [&_p]:text-xs [&_p]:text-[#a1a19b]"><div><h2>关联工地</h2><p>施工队当前参与的项目</p></div></div><div className={linkedListClass}>{linked.map(x=><Link href={`/projects/${x.id}`} key={x.id}><MapPin size={17}/><span><strong>{x.name}</strong><small>{x.address}</small></span><StatusBadge status={x.status}/></Link>)}</div></section></div><TeamForm open={edit} onOpenChange={setEdit} value={item}/></>;
}

export function ProjectDetail({ id }:{id:string}) {
  const [edit,setEdit]=useState(false);const project=useQuery({queryKey:['projects',id],queryFn:({signal})=>projectsApi.get(id,signal)});const workers=useQuery({queryKey:['workers','options'],queryFn:({signal})=>workersApi.list({pageSize:50},signal)});const teams=useQuery({queryKey:['teams','options'],queryFn:({signal})=>teamsApi.list({pageSize:50},signal)});if(project.isPending)return <LoadingState/>;if(project.isError)return <ErrorState error={project.error} retry={()=>void project.refetch()}/>;const item=project.data;const linked=workers.data?.items.filter(x=>item.workerIds.includes(x.id))||[];
  return <><DetailHeader back="/projects" eyebrow="工地 / 项目详情" title={item.name} subtitle={item.address} status={<StatusBadge status={item.status}/>}><PermissionGate permission="workers:write"><Button onClick={()=>setEdit(true)}><Edit3 size={15}/>编辑项目</Button></PermissionGate></DetailHeader><Summary items={[{label:'累计用料',value:formatMoney(item.materialTotal)},{label:'关联油漆工',value:`${item.workerIds.length} 人`},{label:'开始时间',value:item.startDate||'未设置'},{label:'结束时间',value:item.endDate||'未设置'}]}/><div className="grid grid-cols-2 gap-3.5 max-[600px]:grid-cols-1"><section className={panelClass}><div className="flex items-start justify-between gap-4 [&_h2]:mb-1 [&_h2]:text-base [&_h2]:font-semibold [&_p]:text-xs [&_p]:text-[#a1a19b]"><div><h2>项目信息</h2><p>用于用料归属和项目统计</p></div></div><dl className="m-0 grid grid-cols-2 gap-[22px] max-[600px]:grid-cols-1 [&_dt]:text-[11px] [&_dt]:text-[#8e9589] [&_dd]:mt-2 [&_dd]:flex [&_dd]:items-center [&_dd]:gap-1 [&_dd]:text-[13px] [&_dd]:text-[#485043]"><div><dt>负责人</dt><dd>{item.manager}</dd></div><div><dt>施工队</dt><dd>{item.teamName||'未指定'}</dd></div><div><dt>开始时间</dt><dd>{item.startDate||'未设置'}</dd></div><div><dt>结束时间</dt><dd>{item.endDate||'未设置'}</dd></div><div className="col-span-full max-[600px]:col-span-1"><dt>项目地址</dt><dd><MapPin size={14}/>{item.address}</dd></div><div className="col-span-full max-[600px]:col-span-1"><dt>备注</dt><dd>{item.note||'暂无备注'}</dd></div></dl></section><section className={panelClass}><div className="flex items-start justify-between gap-4 [&_h2]:mb-1 [&_h2]:text-base [&_h2]:font-semibold [&_p]:text-xs [&_p]:text-[#a1a19b]"><div><h2>关联油漆工</h2><p>项目用料仍计入油漆工往来账</p></div></div><div className={linkedListClass}>{linked.map(x=><Link href={`/workers/${x.id}`} key={x.id}><span className="grid size-7 shrink-0 place-items-center rounded-[7px] bg-[#e8eee4] text-[11px] text-[#617557]">{x.name[0]}</span><span><strong>{x.name}</strong><small><Phone size={11}/>{x.phone}</small></span><em>{x.teamName||'独立油漆工'}</em></Link>)}</div></section></div><ProjectForm open={edit} onOpenChange={setEdit} value={item} teams={teams.data?.items||[]} workers={workers.data?.items||[]}/></>;
}
