'use client';
import { useEffect } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Dialog, DialogContent, DialogDescription, DialogTitle } from '@/components/ui/dialog';
import { projectInputSchema, teamInputSchema, workerInputSchema, type Project, type ProjectInput, type Team, type TeamInput, type Worker, type WorkerInput } from './schema';
import { projectsApi, teamsApi, workersApi } from '@/lib/api/customers';
import { errorMessage } from '@/lib/api/errors';

type BaseProps<T> = { open: boolean; onOpenChange: (open: boolean) => void; value?: T; onSuccess?: (value: T) => void };
const formClass = "flex flex-col gap-4 [&>label>span]:mb-2 [&>label>span]:block [&>label>span]:text-xs [&>label>span]:text-[#70786b] [&_textarea]:min-h-[72px] [&_textarea]:w-full [&_textarea]:resize-y [&_textarea]:rounded-lg [&_textarea]:border [&_textarea]:border-[#deded9] [&_textarea]:px-3 [&_textarea]:py-2.5 [&_textarea]:text-sm";
const gridClass = "grid grid-cols-2 gap-x-3 gap-y-3.5 max-[600px]:grid-cols-1 [&_label>span]:mb-2 [&_label>span]:block [&_label>span]:text-xs [&_label>span]:text-[#70786b] [&_select]:h-10 [&_select]:w-full [&_select]:rounded-lg [&_select]:border [&_select]:border-[#deded9] [&_select]:bg-white [&_select]:px-3 [&_select]:text-xs [&_select]:text-[#52584f]";
function FieldError({ message }: { message?: string }) { return message ? <p className="mt-1.5 text-xs text-[#a34e40]">{message}</p> : null; }

export function WorkerForm({ open, onOpenChange, value, teams, onSuccess }: BaseProps<Worker> & { teams: Team[] }) {
  const client = useQueryClient();
  const form = useForm<WorkerInput>({ resolver: zodResolver(workerInputSchema), defaultValues: { name:'',phone:'',wechat:'',teamId:null,status:'ACTIVE',note:'' } });
  useEffect(() => { if(open) form.reset(value ? { name:value.name,phone:value.phone,wechat:value.wechat??'',teamId:value.teamId,status:value.status,note:value.note,version:value.version } : { name:'',phone:'',wechat:'',teamId:null,status:'ACTIVE',note:'' }); }, [open, value, form]);
  const mutation = useMutation({ mutationFn:(input:WorkerInput)=>value?workersApi.update(value.id,input):workersApi.create(input), onSuccess:async(saved)=>{await client.invalidateQueries({queryKey:['workers']});toast.success(value?'油漆工资料已更新':'油漆工已新增');onOpenChange(false);onSuccess?.(saved);}, onError:(error)=>form.setError('root',{message:errorMessage(error)}) });
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogTitle>{value?'编辑油漆工':'新增油漆工'}</DialogTitle><DialogDescription>账务默认归属油漆工本人，施工队仅用于成员和统计汇总。</DialogDescription><form className={formClass} onSubmit={form.handleSubmit((input)=>mutation.mutate(input))}><div className={gridClass}><label><span>姓名 *</span><Input {...form.register('name')} /><FieldError message={form.formState.errors.name?.message} /></label><label><span>手机号 *</span><Input inputMode="tel" {...form.register('phone')} /><FieldError message={form.formState.errors.phone?.message} /></label><label><span>微信号</span><Input {...form.register('wechat')} /></label><label><span>所属施工队</span><select {...form.register('teamId',{setValueAs:(v)=>v||null})}><option value="">不加入施工队</option>{teams.filter(x=>x.status==='ACTIVE'||x.id===value?.teamId).map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><label><span>状态</span><select {...form.register('status')}><option value="ACTIVE">正常</option><option value="DISABLED">已停用</option></select></label></div><label><span>备注</span><textarea {...form.register('note')} placeholder="合作偏好、价格说明等" /></label>{form.formState.errors.root&&<div className="rounded-lg border border-[#efd8d2] bg-[#fcf2ef] p-2.5 text-left text-xs text-[#a34e40]" role="alert">{form.formState.errors.root.message}</div>}<div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={()=>onOpenChange(false)}>取消</Button><Button disabled={mutation.isPending}>{mutation.isPending?'正在保存…':'保存资料'}</Button></div></form></DialogContent></Dialog>;
}

export function TeamForm({ open, onOpenChange, value }: BaseProps<Team>) {
  const client=useQueryClient();const form=useForm<TeamInput>({resolver:zodResolver(teamInputSchema),defaultValues:{name:'',leader:'',phone:'',status:'ACTIVE',note:''}});
  useEffect(()=>{if(open)form.reset(value?{name:value.name,leader:value.leader,phone:value.phone,status:value.status,note:value.note,version:value.version}:{name:'',leader:'',phone:'',status:'ACTIVE',note:''});},[open,value,form]);
  const mutation=useMutation({mutationFn:(input:TeamInput)=>value?teamsApi.update(value.id,input):teamsApi.create(input),onSuccess:async()=>{await client.invalidateQueries({queryKey:['teams']});toast.success(value?'施工队资料已更新':'施工队已新增');onOpenChange(false);},onError:(error)=>form.setError('root',{message:errorMessage(error)})});
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogTitle>{value?'编辑施工队':'新增施工队'}</DialogTitle><DialogDescription>施工队不是独立账务主体，金额由成员数据聚合。</DialogDescription><form className={formClass} onSubmit={form.handleSubmit((x)=>mutation.mutate(x))}><div className={gridClass}><label><span>施工队名称 *</span><Input {...form.register('name')} /><FieldError message={form.formState.errors.name?.message}/></label><label><span>负责人 *</span><Input {...form.register('leader')} /><FieldError message={form.formState.errors.leader?.message}/></label><label><span>联系电话 *</span><Input {...form.register('phone')} /><FieldError message={form.formState.errors.phone?.message}/></label><label><span>状态</span><select {...form.register('status')}><option value="ACTIVE">正常</option><option value="DISABLED">已停用</option></select></label></div><label><span>备注</span><textarea {...form.register('note')} /></label>{form.formState.errors.root&&<div className="rounded-lg border border-[#efd8d2] bg-[#fcf2ef] p-2.5 text-left text-xs text-[#a34e40]">{form.formState.errors.root.message}</div>}<div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={()=>onOpenChange(false)}>取消</Button><Button disabled={mutation.isPending}>保存资料</Button></div></form></DialogContent></Dialog>;
}

export function ProjectForm({ open,onOpenChange,value,teams,workers,onSuccess,defaultWorkerId }:BaseProps<Project>&{teams:Team[];workers:Worker[];defaultWorkerId?:string}) {
  const client=useQueryClient();const form=useForm<ProjectInput>({resolver:zodResolver(projectInputSchema),defaultValues:{name:'',address:'',manager:'',workerIds:[],teamId:null,startDate:null,endDate:null,status:'PLANNING',note:''}});
  useEffect(()=>{if(open)form.reset(value?{name:value.name,address:value.address,manager:value.manager,workerIds:value.workerIds,teamId:value.teamId,startDate:value.startDate,endDate:value.endDate,status:value.status,note:value.note,version:value.version}:{name:'',address:'',manager:'',workerIds:defaultWorkerId?[defaultWorkerId]:[],teamId:null,startDate:null,endDate:null,status:'PLANNING',note:''});},[open,value,form,defaultWorkerId]);
  const mutation=useMutation({mutationFn:(input:ProjectInput)=>value?projectsApi.update(value.id,input):projectsApi.create(input),onSuccess:async(saved)=>{await client.invalidateQueries({queryKey:['projects']});toast.success(value?'项目资料已更新':'项目已新增');onOpenChange(false);onSuccess?.(saved);},onError:(error)=>form.setError('root',{message:errorMessage(error)})});
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-w-[680px]"><DialogTitle>{value?'编辑工地 / 项目':'新增工地 / 项目'}</DialogTitle><DialogDescription>项目用于明确材料去向，不改变油漆工的账务归属。</DialogDescription><form className={formClass} onSubmit={form.handleSubmit((x)=>mutation.mutate(x))}><div className={gridClass}><label><span>项目名称 *</span><Input {...form.register('name')} /><FieldError message={form.formState.errors.name?.message}/></label><label><span>负责人 *</span><Input {...form.register('manager')} /><FieldError message={form.formState.errors.manager?.message}/></label><label className="col-span-full"><span>项目地址 *</span><Input {...form.register('address')} /><FieldError message={form.formState.errors.address?.message}/></label><label><span>施工队</span><select {...form.register('teamId',{setValueAs:v=>v||null})}><option value="">不指定</option>{teams.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><label><span>项目状态</span><select {...form.register('status')}><option value="PLANNING">筹备中</option><option value="ACTIVE">进行中</option><option value="COMPLETED">已完成</option><option value="CANCELLED">已取消</option></select></label><label><span>开始时间</span><Input type="date" {...form.register('startDate',{setValueAs:v=>v||null})}/></label><label><span>结束时间</span><Input type="date" {...form.register('endDate',{setValueAs:v=>v||null})}/><FieldError message={form.formState.errors.endDate?.message}/></label></div><fieldset className="m-0 grid grid-cols-3 gap-1.5 rounded-lg border border-[#e5e6e1] p-3 max-[600px]:grid-cols-2 [&>legend]:px-1 [&>legend]:text-xs [&>legend]:text-[#70786b] [&>label]:flex [&>label]:items-center [&>label]:gap-2 [&>label]:rounded-md [&>label]:bg-[#f7f8f4] [&>label]:p-2 [&>label>span]:text-xs [&>label>span]:text-[#46523e] [&_small]:mt-1 [&_small]:block [&_small]:text-[9px] [&_small]:text-[#989e91]"><legend>关联油漆工 *</legend>{workers.filter(x=>x.status==='ACTIVE'||value?.workerIds.includes(x.id)).map(x=><label key={x.id}><input type="checkbox" value={x.id} {...form.register('workerIds')}/><span>{x.name}<small>{x.teamName||'独立油漆工'}</small></span></label>)}</fieldset><FieldError message={form.formState.errors.workerIds?.message}/><label><span>备注</span><textarea {...form.register('note')} /></label>{form.formState.errors.root&&<div className="rounded-lg border border-[#efd8d2] bg-[#fcf2ef] p-2.5 text-left text-xs text-[#a34e40]">{form.formState.errors.root.message}</div>}<div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={()=>onOpenChange(false)}>取消</Button><Button disabled={mutation.isPending}>保存项目</Button></div></form></DialogContent></Dialog>;
}
